# Generated by Django 4.0.3 on 2022-04-06 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='description',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_list', to='events.event'),
        ),
    ]
