# Generated by Django 4.0.3 on 2022-04-06 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='comment',
            new_name='message',
        ),
    ]
